### ISSUE TITLE
Exchange breaks with nested directories

### ISSUE THREAD

**Issue by 0nebody** [LibreTexts/ngshare_exchange#17]
Assignment collection fails when a submission has a nested folder structure.

Occurs when:  `"{ path": "folder1/folder2/file.txt", ...`

https://github.com/LibreTexts/ngshare_exchange/blob/407b6f924b645978026c1806a67b9d9bd185ff29/ngshare_exchange/exchange.py#L175-L177

**Comment by Lawrence37** [comment]
Fixed with bd6be8b and merged to master.
