### ISSUE TITLE
update ngshare-exchange 0.5.1

### ISSUE THREAD

**Issue by orboan** [LibreTexts/ngshare_exchange#20]
Hello,
while installing ngshare_exchange 0.5.1 (latest available using pip) it says it needs nbgrader==0.7.0.dev0, but nbgrader 0.7.0 is already released.

Can you publish a new version with this dependency updated in pypi.org?

I checked you updated the dependency in setup.py.

Thank you.

[nbgrader releases](https://github.com/jupyter/nbgrader/releases)

**Comment by moorepants** [comment]
It is updated in the Github repo.

**Comment by TimStewartJ** [comment]
Closing since the newest version on pypi has its requirements set correctly.
